language: objective-c
xcode_project: skypeweb4adium.xcodeproj
xcode_scheme: skypeweb4adium
before_install:
  - cd adium; make | tail; cd ..
after_success:
  - xctool -project skypeweb4adium.xcodeproj -scheme skypeweb4adium -configuration Release build
